server:
  port: 8097

spring:
  datasource:
    hikari:
      maxLifeTime: 600000
    password: btadmin
    url: jdbc:mysql://54.255.153.46:3306/traditionalyoga?useSSL=false
    username: btadmin
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: zozumguggkfkeath
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: amanchasumukesh08@gmail.com

yoga:
  credentials:
    body: "Hi, \r\n \r\n Your Login Credentials are : \r\n UserId : {0} \r\n Password\
      \ : {1}"
  otp:
    body: "Hi, \r\n \r\n OTP for Email Verification. \r\n {0}"
